### ISSUE TITLE
Recherche template

### ISSUE THREAD

**Issue by moussadiallo** [moussadiallo/daraa#1]
Rechercher un template moderne pour le site.

**Comment by moussadiallo** [comment]
résolu

**Comment by cheikhomaro** [comment]
Bonjour grand comme promis j'ai ouver un compte Gitlab mon userName c'est Cheikhouna!Bne jrnée cordialement! 

```
Le Vendredi 14 octobre 2016 20h42, moussa diallo <notifications@github.com> a écrit :
```

 Rechercher un template moderne pour le site.—

**Comment by moussadiallo** [comment]
Bonjour,
ok c'est bon je t'ai rajouté sur e proje DaaraJi sur gitlab

2016-10-15 14:08 GMT+01:00 Cheikh Omar Sall notifications@github.com:
